<?php

declare(strict_types=1);

namespace Pam\Native\Internal;

use JsonException;
use RuntimeException;

final class PamPhpPreloader
{
    private const VERSION = 1;

    private function __construct()
    {
    }

    /**
     * @return array{components: int, preload: string, manifest: string}
     */
    public static function optimize(string $sourcePath, string $cachePath): array
    {
        $components = PamPhpCompiler::compileDirectory($sourcePath, $cachePath);
        $cacheRoot = realpath($cachePath);
        if ($cacheRoot === false) {
            throw new RuntimeException('PAM optimization cache could not be resolved.');
        }

        $entries = [];
        foreach ($components as $component) {
            $classFile = realpath($component->classFile);
            if (
                $classFile === false
                || !str_starts_with($classFile, $cacheRoot.DIRECTORY_SEPARATOR)
            ) {
                throw new RuntimeException('Compiled PAM class escaped the optimization cache.');
            }
            $sha256 = hash_file('sha256', $classFile);
            if ($sha256 === false) {
                throw new RuntimeException("Cannot fingerprint compiled PAM class {$classFile}.");
            }
            $entries[] = [
                'class' => $component->className,
                'tag' => $component->tag,
                'file' => basename($classFile),
                'sha256' => $sha256,
            ];
        }
        usort(
            $entries,
            static fn (array $left, array $right): int =>
                $left['class'] <=> $right['class'],
        );

        $manifest = [
            'version' => self::VERSION,
            'components' => $entries,
        ];
        try {
            $json = json_encode(
                $manifest,
                JSON_THROW_ON_ERROR | JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES,
            );
        } catch (JsonException $error) {
            throw new RuntimeException('Cannot encode PAM preload manifest.', previous: $error);
        }

        $manifestPath = $cacheRoot.DIRECTORY_SEPARATOR.'pam-preload.json';
        $preloadPath = $cacheRoot.DIRECTORY_SEPARATOR.'pam-preload.php';
        self::writeAtomic($manifestPath, $json."\n");
        self::writeAtomic($preloadPath, self::preloadSource($entries));

        return [
            'components' => count($entries),
            'preload' => $preloadPath,
            'manifest' => $manifestPath,
        ];
    }

    /** @param list<array{class: string, tag: string, file: string, sha256: string}> $entries */
    private static function preloadSource(array $entries): string
    {
        $files = array_column($entries, 'file');
        $classes = array_column($entries, 'class');
        $export = var_export($files, true);
        $classExport = var_export($classes, true);

        return <<<PHP
<?php

declare(strict_types=1);

// Generated by PAM Native. The paths stay relative so signed bundles remain relocatable.
foreach ({$export} as \$file) {
    \$path = __DIR__.DIRECTORY_SEPARATOR.\$file;
    if (!is_file(\$path)) {
        throw new RuntimeException("Missing preloaded PAM component {\$file}.");
    }
    if (function_exists('opcache_compile_file')) {
        @opcache_compile_file(\$path);
    }
    require_once \$path;
}
\Pam\Native\Internal\PamPhpRegistry::preloadMetadata({$classExport});

PHP;
    }

    private static function writeAtomic(string $path, string $contents): void
    {
        $temporary = $path.'.'.bin2hex(random_bytes(8)).'.tmp';
        if (file_put_contents($temporary, $contents, LOCK_EX) === false) {
            throw new RuntimeException("Cannot write PAM optimization file {$path}.");
        }
        if (!rename($temporary, $path)) {
            @unlink($temporary);
            throw new RuntimeException("Cannot publish PAM optimization file {$path}.");
        }
    }
}
