<?php

declare(strict_types=1);

namespace Pam\Native;

final readonly class Style
{
    public function __construct(
        public ?float $width = null,
        public ?float $height = null,
        public ?float $flexGrow = null,
        public ?float $padding = null,
        public ?float $paddingHorizontal = null,
        public ?float $paddingVertical = null,
        public ?float $gap = null,
        public ?float $margin = null,
        public ?float $marginHorizontal = null,
        public ?float $marginVertical = null,
        public ?float $minWidth = null,
        public ?float $minHeight = null,
        public ?float $maxWidth = null,
        public ?float $maxHeight = null,
        public ?int $backgroundColor = null,
        public ?int $textColor = null,
        public ?float $fontSize = null,
        public ?float $borderRadius = null,
        public ?float $borderWidth = null,
        public ?int $borderColor = null,
        public ?float $opacity = null,
        public ?Align $alignItems = null,
        public ?Align $alignSelf = null,
        public ?Justify $justifyContent = null,
        public ?TextAlignment $textAlign = null,
        public ?int $fontWeight = null,
        public ?float $elevation = null,
        public ?float $translationX = null,
        public ?float $translationY = null,
        public ?float $scaleX = null,
        public ?float $scaleY = null,
        public ?float $rotation = null,
        public ?float $letterSpacing = null,
        public ?float $lineHeight = null,
        public ?int $zIndex = null,
        public ?Overflow $overflow = null,
        public ?FlexDirection $flexDirection = null,
        public ?float $flexShrink = null,
        public ?float $paddingLeft = null,
        public ?float $paddingTop = null,
        public ?float $paddingRight = null,
        public ?float $paddingBottom = null,
        public ?float $marginLeft = null,
        public ?float $marginTop = null,
        public ?float $marginRight = null,
        public ?float $marginBottom = null,
        public ?PositionType $positionType = null,
        public ?float $left = null,
        public ?float $top = null,
        public ?float $right = null,
        public ?float $bottom = null,
        public ?float $aspectRatio = null,
        public ?float $borderTopLeftRadius = null,
        public ?float $borderTopRightRadius = null,
        public ?float $borderBottomRightRadius = null,
        public ?float $borderBottomLeftRadius = null,
        public ?float $borderLeftWidth = null,
        public ?float $borderTopWidth = null,
        public ?float $borderRightWidth = null,
        public ?float $borderBottomWidth = null,
        public ?TextDecoration $textDecoration = null,
        public ?TextTransform $textTransform = null,
        public ?FontStyle $fontStyle = null,
        public ?float $widthPercent = null,
        public ?float $heightPercent = null,
        public ?float $maxWidthPercent = null,
        public ?float $maxHeightPercent = null,
        public ?PointerEvents $pointerEvents = null,
        public ?int $numberOfLines = null,
        public ?int $tintColor = null,
        public ?int $placeholderColor = null,
        public ?int $animationDurationMs = null,
        public ?bool $animateChanges = null,
        public ?bool $safeAreaBottom = null,
        public ?float $blurRadius = null,
        public ?string $fontFamily = null,
        public ?bool $visible = null,
        public ?ImageFit $imageFit = null,
        public ?bool $marginLeftAuto = null,
        public ?float $translationXPercent = null,
        public ?AnimationKind $animationKind = null,
        public ?int $gridColumns = null,
        public ?int $gridSpan = null,
        public ?int $gridSpanSm = null,
        public ?int $gridSpanMd = null,
        public ?int $gridSpanLg = null,
        public ?int $gridSpanXl = null,
        public ?int $gridOffset = null,
        public ?int $gridOffsetSm = null,
        public ?int $gridOffsetMd = null,
        public ?int $gridOffsetLg = null,
        public ?int $gridOffsetXl = null,
        public ?int $gridOrder = null,
        public ?int $gridOrderSm = null,
        public ?int $gridOrderMd = null,
        public ?int $gridOrderLg = null,
        public ?int $gridOrderXl = null,
        public ?float $gridColumnGap = null,
        public ?float $gridRowGap = null,
        public ?LayoutDirection $layoutDirection = null,
        public ?FlexWrap $flexWrap = null,
    ) {
    }

    /** @return array<int, float|int|bool|string> */
    public function properties(): array
    {
        $properties = [];

        foreach ([
            PropKey::Width->value => $this->width,
            PropKey::Height->value => $this->height,
            PropKey::FlexGrow->value => $this->flexGrow,
            PropKey::Padding->value => $this->padding,
            PropKey::PaddingHorizontal->value => $this->paddingHorizontal,
            PropKey::PaddingVertical->value => $this->paddingVertical,
            PropKey::Gap->value => $this->gap,
            PropKey::Margin->value => $this->margin,
            PropKey::MarginHorizontal->value => $this->marginHorizontal,
            PropKey::MarginVertical->value => $this->marginVertical,
            PropKey::MinWidth->value => $this->minWidth,
            PropKey::MinHeight->value => $this->minHeight,
            PropKey::MaxWidth->value => $this->maxWidth,
            PropKey::MaxHeight->value => $this->maxHeight,
            PropKey::BackgroundColor->value => $this->backgroundColor,
            PropKey::TextColor->value => $this->textColor,
            PropKey::FontSize->value => $this->fontSize,
            PropKey::BorderRadius->value => $this->borderRadius,
            PropKey::BorderWidth->value => $this->borderWidth,
            PropKey::BorderColor->value => $this->borderColor,
            PropKey::Opacity->value => $this->opacity,
            PropKey::AlignItems->value => $this->alignItems?->value,
            PropKey::AlignSelf->value => $this->alignSelf?->value,
            PropKey::JustifyContent->value => $this->justifyContent?->value,
            PropKey::TextAlign->value => $this->textAlign?->value,
            PropKey::FontWeight->value => $this->fontWeight,
            PropKey::Elevation->value => $this->elevation,
            PropKey::TranslationX->value => $this->translationX,
            PropKey::TranslationY->value => $this->translationY,
            PropKey::ScaleX->value => $this->scaleX,
            PropKey::ScaleY->value => $this->scaleY,
            PropKey::Rotation->value => $this->rotation,
            PropKey::LetterSpacing->value => $this->letterSpacing,
            PropKey::LineHeight->value => $this->lineHeight,
            PropKey::ZIndex->value => $this->zIndex,
            PropKey::Overflow->value => $this->overflow?->value,
            PropKey::FlexDirection->value => $this->flexDirection?->value,
            PropKey::FlexShrink->value => $this->flexShrink,
            PropKey::PaddingLeft->value => $this->paddingLeft,
            PropKey::PaddingTop->value => $this->paddingTop,
            PropKey::PaddingRight->value => $this->paddingRight,
            PropKey::PaddingBottom->value => $this->paddingBottom,
            PropKey::MarginLeft->value => $this->marginLeft,
            PropKey::MarginTop->value => $this->marginTop,
            PropKey::MarginRight->value => $this->marginRight,
            PropKey::MarginBottom->value => $this->marginBottom,
            PropKey::PositionType->value => $this->positionType?->value,
            PropKey::Left->value => $this->left,
            PropKey::Top->value => $this->top,
            PropKey::Right->value => $this->right,
            PropKey::Bottom->value => $this->bottom,
            PropKey::AspectRatio->value => $this->aspectRatio,
            PropKey::BorderTopLeftRadius->value => $this->borderTopLeftRadius,
            PropKey::BorderTopRightRadius->value => $this->borderTopRightRadius,
            PropKey::BorderBottomRightRadius->value => $this->borderBottomRightRadius,
            PropKey::BorderBottomLeftRadius->value => $this->borderBottomLeftRadius,
            PropKey::BorderLeftWidth->value => $this->borderLeftWidth,
            PropKey::BorderTopWidth->value => $this->borderTopWidth,
            PropKey::BorderRightWidth->value => $this->borderRightWidth,
            PropKey::BorderBottomWidth->value => $this->borderBottomWidth,
            PropKey::TextDecoration->value => $this->textDecoration?->value,
            PropKey::TextTransform->value => $this->textTransform?->value,
            PropKey::FontStyle->value => $this->fontStyle?->value,
            PropKey::WidthPercent->value => $this->widthPercent,
            PropKey::HeightPercent->value => $this->heightPercent,
            PropKey::MaxWidthPercent->value => $this->maxWidthPercent,
            PropKey::MaxHeightPercent->value => $this->maxHeightPercent,
            PropKey::PointerEvents->value => $this->pointerEvents?->value,
            PropKey::NumberOfLines->value => $this->numberOfLines,
            PropKey::TintColor->value => $this->tintColor,
            PropKey::PlaceholderColor->value => $this->placeholderColor,
            PropKey::AnimationDurationMs->value => $this->animationDurationMs,
            PropKey::AnimateChanges->value => $this->animateChanges,
            PropKey::SafeAreaBottom->value => $this->safeAreaBottom,
            PropKey::BlurRadius->value => $this->blurRadius,
            PropKey::FontFamily->value => $this->fontFamily,
            PropKey::Visible->value => $this->visible,
            PropKey::ImageFit->value => $this->imageFit?->value,
            PropKey::MarginLeftAuto->value => $this->marginLeftAuto,
            PropKey::TranslationXPercent->value => $this->translationXPercent,
            PropKey::AnimationKind->value => $this->animationKind?->value,
            PropKey::GridColumns->value => $this->gridColumns,
            PropKey::GridSpan->value => $this->gridSpan,
            PropKey::GridSpanSm->value => $this->gridSpanSm,
            PropKey::GridSpanMd->value => $this->gridSpanMd,
            PropKey::GridSpanLg->value => $this->gridSpanLg,
            PropKey::GridSpanXl->value => $this->gridSpanXl,
            PropKey::GridOffset->value => $this->gridOffset,
            PropKey::GridOffsetSm->value => $this->gridOffsetSm,
            PropKey::GridOffsetMd->value => $this->gridOffsetMd,
            PropKey::GridOffsetLg->value => $this->gridOffsetLg,
            PropKey::GridOffsetXl->value => $this->gridOffsetXl,
            PropKey::GridOrder->value => $this->gridOrder,
            PropKey::GridOrderSm->value => $this->gridOrderSm,
            PropKey::GridOrderMd->value => $this->gridOrderMd,
            PropKey::GridOrderLg->value => $this->gridOrderLg,
            PropKey::GridOrderXl->value => $this->gridOrderXl,
            PropKey::GridColumnGap->value => $this->gridColumnGap,
            PropKey::GridRowGap->value => $this->gridRowGap,
            PropKey::LayoutDirection->value => $this->layoutDirection?->value,
            PropKey::FlexWrap->value => $this->flexWrap?->value,
        ] as $key => $value) {
            if ($value !== null) {
                $properties[$key] = $value;
            }
        }

        return $properties;
    }
}
